#!/bin/sh

db=${1}

if [ -z "${db}" -o ! -d ${db} ]; then
    echo "syntax: $0 <db-directory> [ psql commands... ]"
    exit 1
fi

shift

port=$(sed -ne 's,^\(.*port.*=[^0-9]*\)\([0-9]*\)\(.*\),\2,p' < ${db}/etc/postgresql/postgresql.conf)

echo port=${port}

psql --host $(pwd)/${db}/var/run -p ${port} ${db} "$@"
