#!/bin/sh

pwd=$(cd ${0%/*}; pwd)

db="$1"

if [ -z "${db}" ]; then
    echo "usage: $0 <dbname=directory>"
    exit 1
fi

set -xe

${pwd}/bin/postgres initdb ${db}
yes | ${pwd}/bin/postgres tune ${db}
${pwd}/bin/postgres run ${db} &
sleep 2
echo "create database ${db}" | ${pwd}/bin/postgres admin ${db}
kill $(cat ${db}/var/run/*.pid)
sleep 2
echo "done"
