#!/bin/sh

pwd=$(cd ${0%/*}; pwd)

db=${1}

if [ -z "${db}" -o ! -d ${db} ]; then
    echo "syntax: $0 <db-directory>"
    exit 1
fi

shift

if screen -list|grep psql; then
    echo not starting a new server
else
    echo "starting inside screen:"
    screen -L -S psql -d -m ${pwd}/bin/postgres run ${db}
    screen -list
fi
